/* ── report.js — PDF report generation ── */

function genReport() {
  if (!CUR) return;
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
  const d = CUR;
  const cDark = [6, 11, 20], cAcc = [0, 150, 190], cPath = [200, 40, 65], cBen = [0, 160, 100], cGray = [88, 105, 130];

  doc.setFillColor(...cDark); doc.rect(0, 0, 210, 26, 'F');
  doc.setTextColor(0, 212, 255); doc.setFont('helvetica', 'bold'); doc.setFontSize(17);
  doc.text('GenomeScan AI', 14, 11);
  doc.setTextColor(180, 210, 235); doc.setFont('helvetica', 'normal'); doc.setFontSize(9.5);
  doc.text('Genomic Variant Analysis Report', 14, 19);
  const rid = 'GS-' + Date.now().toString(36).toUpperCase();
  doc.setTextColor(90, 130, 170); doc.setFontSize(7.5);
  doc.text(`ID: ${rid}`, 142, 9);
  doc.text(`Date: ${new Date().toLocaleString()}`, 142, 15);
  doc.text('Reference: GRCh38/hg38', 142, 21);

  doc.setFillColor(255, 248, 220); doc.rect(0, 26, 210, 8, 'F');
  doc.setTextColor(140, 80, 0); doc.setFontSize(7);
  doc.text('⚠  Research use only — not validated for clinical diagnostics — must be interpreted by a qualified genetics professional', 6, 31.5);

  let y = 42;
  const sec = (title) => {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFillColor(...cAcc); doc.rect(14, y - 3, 3, 9, 'F');
    doc.setTextColor(...cDark); doc.setFont('helvetica', 'bold'); doc.setFontSize(11);
    doc.text(title, 20, y + 4); y += 12;
  };
  const row = (label, val) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5);
    doc.setTextColor(...cGray); doc.text(label + ':', 20, y);
    doc.setTextColor(...cDark); doc.text(String(val), 68, y); y += 6.5;
  };

  sec('Variant Summary');
  row('Variant', `${d.variant.chr}:${d.variant.pos}  ${d.variant.ref}>${d.variant.alt}`);
  row('Gene', `${d.gene.sym} — ${d.gene.loc}`);
  row('Reference Genome', 'GRCh38/hg38');
  row('Position', d.stats.pos); y += 3;

  sec('Pathogenicity Classification');
  const sc = d.path.score;
  const sCol = sc >= 80 ? cPath : sc >= 60 ? [210, 90, 0] : sc >= 40 ? [170, 120, 0] : cBen;
  doc.setFillColor(...sCol); doc.rect(20, y, 28, 18, 'F');
  doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold'); doc.setFontSize(22);
  doc.text(`${sc}`, 26, y + 13);
  doc.setTextColor(...sCol); doc.setFontSize(13);
  doc.text(d.path.verdict, 54, y + 9);
  doc.setTextColor(...cGray); doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5);
  doc.text(`Model confidence: ${d.path.conf}%`, 54, y + 16); y += 26;

  sec('Disease Associations (Top 5)');
  d.diseases.forEach((dis, i) => {
    doc.setTextColor(...cGray); doc.setFontSize(8.5);
    doc.text(dis.name, 20, y);
    doc.setTextColor(...cDark); doc.text(`${dis.prob}%`, 108, y);
    doc.setFillColor(215, 222, 235); doc.rect(116, y - 4.5, 62, 5, 'F');
    const bc = i === 0 ? cPath : cAcc;
    doc.setFillColor(...bc); doc.rect(116, y - 4.5, 62 * dis.prob / 100, 5, 'F');
    y += 8;
  }); y += 3;

  sec(`Gene: ${d.gene.sym}`);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(...cGray);
  doc.text('Function:', 20, y); doc.setTextColor(...cDark);
  const fnLines = doc.splitTextToSize(d.gene.fn, 165);
  doc.text(fnLines, 20, y + 6); y += fnLines.length * 5 + 12;
  doc.setTextColor(...cGray); doc.text('Associated conditions:', 20, y);
  doc.setTextColor(...cDark); doc.text(d.gene.tags.join(', '), 20, y + 6); y += 14;

  sec('Variant Statistics');
  row('Mutation Type', d.stats.type + ' — ' + d.stats.typeSub);
  row('GC Content', d.stats.gc + '% (flanking ±64 bp)');
  row('Shannon Entropy', d.stats.ent.toString());
  row('CpG Context', d.stats.cpg); y += 3;

  sec('Methodology & Model Details');
  ['Model: DNABERT-2-117M fine-tuned on ClinVar (30,000 variants)',
    'Sequence context: ±64 bp flanking the variant (129 bp total)',
    'Tokenization: overlapping 6-mer scheme per DNABERT-2',
    'Thresholds: <20% Benign · 20-40% L.Benign · 40-60% VUS · 60-80% L.Path. · >80% Pathogenic'
  ].forEach(m => {
    doc.setFontSize(8.5); doc.setTextColor(...cGray); doc.text('•  ' + m, 20, y); y += 6;
  }); y += 4;

  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFillColor(248, 244, 240); doc.rect(14, y, 182, 24, 'F');
  doc.setTextColor(...cGray); doc.setFont('helvetica', 'bold'); doc.setFontSize(8);
  doc.text('DISCLAIMER', 18, y + 7);
  doc.setFont('helvetica', 'normal');
  const dis2 = doc.splitTextToSize('This report is generated by an AI research model (DNABERT-2) and has not been validated for clinical use. Results must be reviewed by a qualified medical genetics professional. The model may not cover novel variants absent from the ClinVar training set.', 172);
  doc.text(dis2, 18, y + 14);

  doc.setFillColor(...cDark); doc.rect(0, 277, 210, 20, 'F');
  doc.setTextColor(80, 120, 160); doc.setFontSize(7);
  doc.text(`GenomeScan AI v1.0  ·  ${rid}  ·  Research Tool`, 14, 285);
  doc.text('Page 1', 190, 285, { align: 'right' });

  doc.save(`GenomeScan_${d.gene.sym}_${rid}.pdf`);
}
